version: '3.8'
services:
  backedn:
    build: ./backend
    container_name: api_backend
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
